### ISSUE TITLE
`CTS` (clear to send) needs to be connected to the `GND` (ground) plane.

### ISSUE THREAD

**Issue by zfields** [sparkfun/ProtoShield_Kit#1]
When this floats, it can indicate to the Blue SMiRF that it is NOT clear to send, which results in no inbound data to the Arduino. If this pin is set to the ground plane, then it will allow the Blue SMiRF to fire at will with no flow control.

**Comment by ToniCorinne** [comment]
We're addressing this issue in the new revision of the board we're working on. Thanks for the feedback!

**Comment by zfields** [comment]
If you want to send me one, I will be happy to test it out! :tada: :package: :neckbeard: :v:

**Comment by zfields** [comment]
I have a cart waiting on sparkfun.com, but before I make the purchase I wanted to know if this issue been addressed in [this product](https://www.sparkfun.com/products/11665)? I looked at the repo, but the last commit was in 2015.
